"""Add parent_child_link table for many-to-many parent-child

Revision ID: 8adc50a73338
Revises: 
Create Date: 2025-10-27 20:13:14.201901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adc50a73338'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parents_child_id_fkey'), 'parents', type_='foreignkey')
    op.drop_column('parents', 'child_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('parents_child_id_fkey'), 'parents', 'children', ['child_id'], ['id'])
    # ### end Alembic commands ###
